"""Initial migration.

Revision ID: 9ef5e6bc8a2f
Revises: 
Create Date: 2024-03-06 10:43:20.960982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef5e6bc8a2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cron_expression', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(length=30), nullable=True),
    sa.Column('daily_rule_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['daily_rule_id'], ['rule.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('birthday',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pre_reminder',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('birthdays_pre_reminders',
    sa.Column('birthday_id', sa.UUID(), nullable=False),
    sa.Column('pre_reminder_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['birthday_id'], ['birthday.id'], ),
    sa.ForeignKeyConstraint(['pre_reminder_id'], ['pre_reminder.id'], ),
    sa.PrimaryKeyConstraint('birthday_id', 'pre_reminder_id')
    )
    op.create_table('notification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('birthday_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['birthday_id'], ['birthday.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('birthdays_pre_reminders')
    op.drop_table('pre_reminder')
    op.drop_table('birthday')
    op.drop_table('user')
    op.drop_table('rule')
    # ### end Alembic commands ###
