"""Refreshed db intiial structure

Revision ID: 598029b3c699
Revises: 
Create Date: 2024-03-12 22:54:06.574607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598029b3c699'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birthday',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('surname', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('notification_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timedelta_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('timedelta', sa.Interval(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('birthdays_notifications',
    sa.Column('birthday_id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['birthday_id'], ['birthday.id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], ),
    sa.PrimaryKeyConstraint('birthday_id', 'notification_id')
    )
    op.create_table('pre_reminder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pre_reminder_type', sa.String(length=16), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['timedelta_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('birthdays_pre_reminders',
    sa.Column('birthday_id', sa.Integer(), nullable=False),
    sa.Column('pre_reminder_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['birthday_id'], ['birthday.id'], ),
    sa.ForeignKeyConstraint(['pre_reminder_id'], ['pre_reminder.id'], ),
    sa.PrimaryKeyConstraint('birthday_id', 'pre_reminder_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birthdays_pre_reminders')
    op.drop_table('pre_reminder')
    op.drop_table('birthdays_notifications')
    op.drop_table('timedelta_rule')
    op.drop_table('notification')
    op.drop_table('birthday')
    # ### end Alembic commands ###
